
clear;clc;close all

load('/media/teamlary/Team_Lary_2/air930/mintsData/mergedMats/aeroqualWithPalas/aeroqualAllWithPalas.mat')


mintsInputs          =  {'PM10ppm' ,'PM25ppm'}
mintsInputLabels     =  {'PM_{10} ppm', 'PM_{2.5} ppm'}   

mintsTargets         =  {'pm1_PALAS','pm2_5_palas','pm4_palas','pm10_palas'}      
mintsTargetLabels    =  {...
                            'PM_{1}'                  ,...
                            'PM_{2.5}'                ,...
                            'PM_{4}'                  ,...
                            'PM_{10}'                 ,...
                        }        

nodeIDs   = {...
                  'aeroqual1',...
                  'aeroqual2',...
                  'aeroqual4'...
                };


pValid = .15;


trainingMatsFolder = "/media/teamlary/Team_Lary_2/air930/mintsData/trainingMats/aeroqual";
modelsMatsFolder   = "/media/teamlary/Team_Lary_2/air930/mintsData/modelsMats/aeroqual";

versionStr = ['modelVersionNN_' datestr(today,'yyyy_mm_dd')];
disp(versionStr)



for nodeIndex = 1:length(nodeIDs)
    nodeID = nodeIDs{nodeIndex}
    
    eval(strcat("aeroqualWithPalas = ",nodeID,"WithPalas;"))
        
    for targetIndex = 1: length(mintsTargets)    
        target = mintsTargets{targetIndex};
        targetLabel = mintsTargetLabels{targetIndex};
  
        display(newline)
        display("Gainin Data set for Node "+ nodeID + " with target output " + target)

         % Getting the Load  Name 
        loadName = getMintsFileNameTraining(trainingMatsFolder,nodeIDs,nodeIndex,...
                                                                target,"trainingMintsAir");

        display("loading : "+ loadName)
        load(loadName)
        
        
        display("Training Now for Node "+  nodeID + ", Target: " + target) 
        tic
        Mdl = fitrnn(In_Train,Out_Train);
        
        display("Training done for Node "+  nodeID + ", Target: " + target)   
        
        display("Training Time:"+  toc)
       
        saveName = getMintsFileNameGeneral(modelsMatsFolder,nodeIDs,nodeIndex,...
                                                    target,versionStr)
                                                
        save(saveName,...
             'Mdl',...
             'In_Train',...
             'Out_Train',...
             'In_Validation',...
             'Out_Validation',...
             'trainingTT',...
             'validatingTT',...
             
             'trainingT',...
             'validatingT',...
             'mintsInputs',...
             'mintsInputLabels',...
             'target',...
             'targetLabel',...
             'nodeID',...
             'mintsInputs',...
             'mintsInputLabels',...
             'pValid' ...
         )
       
        clearvars -except...
               versionStr ...
               rawMatsFolder mergedMatsFolder ...
               trainingMatsFolder modelsMatsFolder...
               nodeIDs nodeIndex nodeID ...
               aeroqualWithPalas ...
               aeroqual1WithPalas ...
               aeroqual2WithPalas ...
               aeroqual4WithPalas ...
               mintsInputs mintsInputLabels ...
               mintsTargets mintsTargetLabels targetIndex ...
               binsPerColumn numberPerBin pValid 




    end
    
end


function currentFileName = getMintsFileNameTraining(folder,nodeIDs,nodeIndex,...
                                                            target,stringIn)
        nodeDataFolder      = folder+ "/"+nodeIDs(nodeIndex);
        currentFileName     = nodeDataFolder+"/"+stringIn + "_" +...
                                    nodeIDs(nodeIndex)+ "_" + ...
                                          target +"_"+...
                                              ".mat";
                                          
    if ~exist(fileparts(currentFileName), 'dir')
       mkdir(fileparts(currentFileName));
    end
end

