close all 
residuesFigTrain      = getMintsFileNameFigPre(plotsFolder,nodeIDs,nodeIndex,target,versionStr +"_trainResidues");
residuesFigTest       = getMintsFileNameFigPre(plotsFolder,nodeIDs,nodeIndex,target,versionStr +"_testResidues") ;

residuesHistFigTrain      = getMintsFileNameFigPre(plotsFolder,nodeIDs,nodeIndex,target,versionStr +"_trainHistResidues");
residuesHistFigTest       = getMintsFileNameFigPre(plotsFolder,nodeIDs,nodeIndex,target,versionStr +"_testHistResidues") ;



drawResiduesPlotMints(Out_Train,...
                                    outTrainEstimate,...
                                    nodeID,...
                                    targetLabel,...
                                    "Residues Plot Training",...
                                    "Palas Spectrometor",...
                                    "Mints Node",...
                                    unit,...
                                    residuesFigTrain);        


drawResiduesPlotMints(Out_Validation,...
                                    outValidEstimate,...
                                    nodeID,...
                                    targetLabel,...
                                    "Residues Plot Testing",...
                                    "Palas Spectrometor",...
                                    "Mints Node",...
                                    unit,...
                                    residuesFigTest);
                        

                    

                             
drawResiduesHistogramPlotMints(Out_Validation,...
                                    outValidEstimate,...
                                    nodeID,...
                                    targetLabel,...
                                    "Residues Histogram Training",...
                                    "Palas Spectrometor",...
                                    "Mints Node",...
                                    unit,...
                                    residuesHistFigTrain);        

                                
                             
drawResiduesHistogramPlotMints(Out_Train,...
                                    outTrainEstimate,...
                                    nodeID,...
                                    targetLabel,...
                                    "Residues Histogram Testing",...
                                    "Palas Spectrometor",...
                                    "Mints Node",...
                                    unit,...
                                    residuesHistFigTest);                                   
%   drawResiduesPlotMints(dataX,...
%                                     dataY,...
%                                     nodeID,...
%                                     estimator,...
%                                     summary,...
%                                     xInstrument,...
%                                     yInstrument,...
%                                     units,...
%                                     saveNameFig)