
function [] = writeGPSGPRMC2csv(fileName)
%    filename: /media/teamlary/Team_Lary_1/gitGubRepos/Lakitha/mintsAirML/firmware/dataProcessing/mints/MINTS_001e06305a12_GPSGPRMC_2019_04_30.csv
%
% Auto-generated by MATLAB on 28-May-2020 17:38:32

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["dateTime", "timestamp", "status", "latitude", "latitudeDirection", "longitude", "longitudeDirection", "speedOverGround", "trueCourse", "dateStamp", "magVariation", "magVariationDirection"];
opts.VariableTypes = ["datetime", "datetime", "categorical", "double", "categorical", "double", "categorical", "double", "string", "datetime", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["trueCourse", "magVariation", "magVariationDirection"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["status", "latitudeDirection", "longitudeDirection", "trueCourse", "magVariation", "magVariationDirection"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "dateTime", "InputFormat", "yyyy-MM-dd HH:mm:ss.SSS");
opts = setvaropts(opts, "timestamp", "InputFormat", "HH:mm:ss");
opts = setvaropts(opts, "dateStamp", "InputFormat", "yyyy-MM-dd");

% Import the data
lk2 = readtable(fileName);

filenameNew = strrep(fileName,"_GPSGPRMC_","_GPSGPRMC2_")
latitudeCoordinate   =  getLatitudeAirMar(lk2.latitude,cellstr(lk2.latitudeDirection));
longitudeCoordinate  =  getLongitudeAirMar(lk2.longitude,cellstr(lk2.longitudeDirection));

lk2.latitudeCoordinate   = latitudeCoordinate;
lk2.longitudeCoordinate  = longitudeCoordinate;

labels =    {'dateTime'           ,
            'timestamp'           ,
            'status'              ,
            'latitudeCoordinate'  ,
            'longitudeCoordinate' ,
            'latitude'            ,
            'latitudeDirection'   ,
            'longitude'           ,
            'longitudeDirection'  ,
            'speedOverGround'     ,
            'trueCourse'          ,
            'dateStamp'           ,
            'magVariation'        ,
            'magVariationDirection'};
        
writetable(lk2(:,labels),filenameNew);


%% Clear temporary variables
clear opts

 end