%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /media/teamlary/Team_Lary_1/gitGubRepos/Lakitha/mintsAirML/firmware/dataProcessing/mints/MINTS_001e06305a12_GPSGPGGA_2019_04_30.csv
%
% Auto-generated by MATLAB on 28-May-2020 16:19:35

%% Clear temporary variables



% clear opts