

clc
clear all
close all 

%  Data Pre Processing for Pre Car Calibration 
% Defining Node IDS 
display("--------MINTS--------")
addpath("../../functions/")

%% loading Palas Data 
load("/media/teamlary/Team_Lary_2/air930/mintsData/referenceMats/palas/palasWSTCOnlyJuly2020.mat");
% Removing GPS Data 
palasData = removevars(palasWSTC,{'latitude','longitude'});

% Loading Mints Data 
rawMatsFolder = "/media/teamlary/Team_Lary_2/air930/mintsData/rawMats/"
% Constructing the input and output data for ML 
mergedMatsFolder = "/media/teamlary/Team_Lary_2/air930/mintsData/mergedMats"

nodeIDs   = {...
                '001e06305a12',...
                '001e06323a12',...
                '001e06318cd1',...
                '001e06305a61',...
                '001e06323a05',...
                '001e06305a57',...
                '001e063059c2',...
                '001e06318c28',...
                '001e06305a6b',...
                '001e063239e3',...
                '001e06305a6c'...
                };

for nodeIndex = 1:length(nodeIDs)

    load(strcat(rawMatsFolder,...
                nodeIDs{nodeIndex},...
                "/deliverables/mintsDataAllRetimed_",...
                nodeIDs{nodeIndex},...
                "_2018_01_01_to_2020_07_20.mat"));


    palasData.dateTime.TimeZone = "utc";
 

    % For mints Data, Removing Sky Cam data - less frequent than 30 seconds
    mintsData =  removevars(mintsDataAll, {'cloudPecentage_002',...
                                                'allRed_002',...
                                                'allGreen_002',...
                                                'allBlue_002',...
                                                'skyRed_002',...
                                                'skyGreen_002',...
                                                'skyBlue_002',...
                                                'cloudRed_002',...
                                                'cloudGreen_002',...
                                                'cloudBlue_002'});

    mintsData.dateTime.TimeZone = "utc";

    % The OPC N2 the pm levels were mixed up 
    mintsData.Properties.VariableNames  = strrep(strrep(strrep(mintsData.Properties.VariableNames,...
                                                                        'pm1_OPCN2','PM10_OPCN2'),...
                                                                        'pm10_OPCN2','PM2_5_OPCN2'),...
                                                                        'pm2_5_OPCN2','PM1_OPCN2');

                                                                    
                                                                    
    %% Geo Bound Mints Nodes 
    % WSTC Coordinates - Only For Training Purposes
    mintsData = gpsCrop(mintsData,32.992179, -96.757777,0.0015,0.0015);
  
    
    mintsWithPalas = rmmissing(synchronize(mintsData,palasData,'intersection'));


    fileNameStr = getMintsRangeNameStr(dateshift(mintsWithPalas.dateTime(1), 'start', 'day'),...
                         dateshift(mintsWithPalas.dateTime(end), 'start', 'day'),...
                         mergedMatsFolder,...
                         nodeIDs,...
                         nodeIndex,...
                         "mintsWithPalas") 

    save(fileNameStr,...
            'mintsWithPalas')                 

   clearvars -except palasData rawMatsFolder mergedMatsFolder nodeIDs ...
                        nodeIndex mintsWithPalas mintsWithPalas ...
                        palasAirAllRetimed S
    
end   




       