


clc
clear all
close all 

%%  Data Pre Processing for Pre Car Calibration 
% Defining Node IDS 
display("--------MINTS--------")
addpath("../../functions/")
% 3259.5316	N	9645.468

% Loading Mints Data 
rawMatsFolder = "/media/teamlary/Team_Lary_2/air930/mintsData/rawMats/"
% Constructing the input and output data for ML 
mergedMatsFolder = "/media/teamlary/Team_Lary_2/air930/mintsData/mergedMats"


% loading AirMar Data From the Cage  
load("/media/teamlary/Team_Lary_2/air930/mintsData/referenceMats/001e0610c0e4/deliverables/mintsDataAllRetimed_30 sec_001e0610c0e4_2019_02_16_to_2019_09_09.mat")
airMarCage = mintsDataAll;
load("/media/teamlary/Team_Lary_2/carMints/referenceMats/001e0610c2e9/deliverables/mintsDataAllRetimed_30 sec_001e0610c2e9_2020_01_07_to_2020_04_24.mat")
airMarCar = mintsDataAll;



airMarAll = [airMarCage;airMarCar];

% Since We are in the US 
airMarAll.longitude_GPGGA(airMarAll.longitude_GPGGA>0,:) = ...
                  -airMarAll.longitude_GPGGA(airMarAll.longitude_GPGGA>0,:);

airMarWSTC =  airMarAll(airMarAll.latitude_GPGGA>32.990 &...
                            airMarAll.latitude_GPGGA<32.994 &...
                                airMarAll.longitude_GPGGA<-96.757 & ...  
                                    airMarAll.longitude_GPGGA>-96.759,:);   
                        
                        

nodeIDs   = {...
                '001e06305a12',...
                '001e06323a12',...
                '001e06318cd1',...
                '001e06305a61',...
                '001e06323a05',...
                '001e06305a57',...
                '001e063059c2',...
                '001e06318c28',...
                '001e06305a6b',...
                '001e063239e3',...
                '001e06305a6c'...
                };

for nodeIndex = 1: length(nodeIDs)

    display("Going Through Node: " + nodeIDs{nodeIndex})
    
    %% Loading Mints 
    load(strcat(rawMatsFolder,...
                nodeIDs{nodeIndex},...
                "/deliverables/mintsDataAllRetimed_",...
                nodeIDs{nodeIndex},...
                "_2019_01_01_to_2020_04_25.mat"));


    % For mints Data, Removing Sky Cam data - less frequent than 30 seconds
    mintsData =  removevars(mintsDataAll, {'cloudPecentage_002',...
                                                'allRed_002',...
                                                'allGreen_002',...
                                                'allBlue_002',...
                                                'skyRed_002',...
                                                'skyGreen_002',...
                                                'skyBlue_002',...
                                                'cloudRed_002',...
                                                'cloudGreen_002',...
                                                'cloudBlue_002'});

    mintsData.dateTime.TimeZone = "utc";

    % The OPC N2 the pm levels were mixed up 
    mintsData.Properties.VariableNames  = strrep(strrep(strrep(mintsData.Properties.VariableNames,...
                                                                        'pm1_OPCN2','PM10_OPCN2'),...
                                                                        'pm10_OPCN2','PM2_5_OPCN2'),...
                                                                        'pm2_5_OPCN2','PM1_OPCN2');

    mintsWithAirMarWSTC = rmmissing(synchronize(mintsData,airMarWSTC,'intersection'));

    fileNameStr = getMintsRangeNameStr(dateshift(mintsWithAirMarWSTC.dateTime(1), 'start', 'day'),...
                         dateshift(mintsWithAirMarWSTC.dateTime(end), 'start', 'day'),...
                         mergedMatsFolder,...
                         nodeIDs,...
                         nodeIndex,...
                         "mintsWithAirMarWSTC") ;

    save(fileNameStr,...
            'mintsWithAirMarWSTC')                 

   clearvars -except palasData rawMatsFolder mergedMatsFolder nodeIDs ...
                        airMarWSTC  ...
                        
    
end   
%        