function aeroqual = aeroqualReader(fileName)
    %% Import data from text file
    % Script for importing data from the following text file:
    %
    %    filename: /media/teamlary/Team_Lary_1/gitGubRepos/Lakitha/mintsAirML/firmware/dataProcessing/aeroqual/AE1day4.csv
    %
    % Auto-generated by MATLAB on 22-Aug-2020 19:35:04

    %% Setup the Import Options and import the data
    opts = delimitedTextImportOptions("NumVariables", 5);

    % Specify range and delimiter
    opts.DataLines = [2, Inf];
    opts.Delimiter = ",";

    % Specify column names and types
    opts.VariableNames = ["dateTime", "MonitorID", "LocationID", "PM10ppm", "PM25ppm"];
    opts.VariableTypes = ["string", "double", "double", "double", "double"];

    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";

    % Specify variable properties
    opts = setvaropts(opts, "dateTime", "WhitespaceRule", "preserve");
    opts = setvaropts(opts, "dateTime", "EmptyFieldRule", "auto");

    % Import the data
    aeroqual = readtable(fileName, opts);

    aeroqual.dateTime = datetime(aeroqual.dateTime, 'InputFormat', 'dd MMM yyyy HH:mm','TimeZone','utc');

    %% Clear temporary variables
    clear opts
end

