function [] = drawAllTimeSeriesPlotsDFW(calibrated,nodeID,givenDate,calibratedFolder,timeZone)
%DRAWALLTIMESERIESPLOTS Summary of this function goes here
%   Detailed explanation goes here
latitudeStringPre = sprintf('%0.8f',calibrated.Latitude(1));
longitudeStringPre =sprintf('%0.8f',calibrated.Longitude(1));
latitudeString = strcat(latitudeStringPre,"^o");
longitudeString =strcat(longitudeStringPre,"^o");


    drawTimeSeriesWithSave2(...
                    calibrated.dateTime,...
                    calibrated.PM1,...
                    nodeID,...
                    strcat(timeZone," Time"),...
                    "PM_{1}(\mug/m^{3})",...
                    strcat("PM_{1}(",latitudeString,",",longitudeString,")"),...
                    givenDate,...
                    calibratedFolder,...
                    strcat("PM1_",timeZone,"_Time"),...
                    false,...
                    100 ...
                    )
                
    drawTimeSeriesWithSave2(...
                    calibrated.dateTime,...
                    calibrated.PM2_5,...
                    nodeID,...
                    strcat(timeZone," Time"),...
                    "PM_{2.5}(\mug/m^{3})",...
                    strcat("PM_{2.5}(",latitudeString,",",longitudeString,")"),...
                    givenDate,...
                    calibratedFolder,...
                    strcat("PM2_5_",timeZone,"_Time"),...
                    false,...
                    100 ...
                    )
    

                            
        drawTimeSeriesWithSave2(...
                    calibrated.dateTime,...
                    calibrated.PM10,...
                    nodeID,...
                    strcat(timeZone," Time"),...
                    "PM_{10}(\mug/m^{3})",...
                    strcat("PM_{10}(",latitudeString,",",longitudeString,")"),...
                    givenDate,...
                    calibratedFolder,...
                    strcat("PM10_",timeZone,"_Time"),...
                    false,...
                    100 ...
                    )
% 

    drawTimeSeriesWithSave2(...
                    calibrated.dateTime,...
                    calibrated.Alveolic,...
                    nodeID,...
                    strcat(timeZone," Time"),...
                    "Alveolic(\mug/m^{3})",...
                    strcat("Alveolic(",latitudeString,",",longitudeString,")"),...
                    givenDate,...
                    calibratedFolder,...
                    strcat("Alveolic_",timeZone,"_Time"),...
                    false,...
                    100 ...
                    )


        drawTimeSeriesWithSave2(...
                    calibrated.dateTime,...
                    calibrated.Thoracic,...
                    nodeID,...
                    strcat(timeZone," Time"),...
                    "Thoracic(\mug/m^{3})",...
                    strcat("Thoracic(",latitudeString,",",longitudeString,")"),...
                    givenDate,...
                    calibratedFolder,...
                    strcat("Thoracic_",timeZone,"_Time"),...
                    false,...
                    100 ...
                    )                
         drawTimeSeriesWithSave2(...
                    calibrated.dateTime,...
                    calibrated.Inhalable,...
                    nodeID,...
                    strcat(timeZone," Time"),...
                    "Inhalable(\mug/m^{3})",...
                    strcat("Inhalable(",latitudeString,",",longitudeString,")"),...
                    givenDate,...
                    calibratedFolder,...
                    strcat("Inhalable_",timeZone,"_Time"),...
                    false,...
                    100 ...
                    ) 
%                    
         drawTimeSeriesWithSave2(...
                    calibrated.dateTime,...
                    calibrated.Temperature,...
                    nodeID,...
                    strcat(timeZone," Time"),...
                    "Temperature",...
                    strcat("Temperature(",latitudeString,",",longitudeString,")"),...
                    givenDate,...
                    calibratedFolder,...
                    strcat("Temperature_",timeZone,"_Time"),...
                    false,...
                    100 ...
                    ) 
          
         drawTimeSeriesWithSave2(...
                    calibrated.dateTime,...
                    calibrated.Humidity,...
                    nodeID,...
                    strcat(timeZone," Time"),...
                    "Humidity",...
                    strcat("Humidity(",latitudeString,",",longitudeString,")"),...
                    givenDate,...
                    calibratedFolder,...
                    strcat("Humidity_",timeZone,"_Time"),...
                    false,...
                    100 ...
                    )                 
          
         drawTimeSeriesWithSave2(...
                    calibrated.dateTime,...
                    calibrated.Pressure,...
                    nodeID,...
                    strcat(timeZone," Time"),...
                    "Pressure",...
                    strcat("Pressure(",latitudeString,",",longitudeString,")"),...
                    givenDate,...
                    calibratedFolder,...
                    strcat("Pressure_",timeZone,"_Time"),...
                    false,...
                    100 ...
                    )           
                
         drawTimeSeriesWithSave2(...
                    calibrated.dateTime,...
                    calibrated.DewPoint,...
                    nodeID,...
                    strcat(timeZone," Time"),...
                    "Dew Point",...
                    strcat("Dew Point(",latitudeString,",",longitudeString,")"),...
                    givenDate,...
                    calibratedFolder,...
                    strcat("DewPoint_",timeZone,"_Time"),...
                    false,...
                    100 ...
                    )             
                 
end

