function [] = drawAllTimeSeriesPlotsLongRanged(calibrated,nodeID,startDate,endDate,folderIn,timeZone)
%DRAWALLTIMESERIESPLOTS Summary of this function goes here
%   Detailed explanation goes here
latitudeStringPre = sprintf('%0.8f',calibrated.latitude_GPSGPGGA(1));
longitudeStringPre =sprintf('%0.8f',calibrated.longitude_GPSGPGGA(1));
latitudeString = strcat(latitudeStringPre,"^o");
longitudeString =strcat(longitudeStringPre,"^o");




    drawTimeSeriesWithSaveLongRanged(...
                    calibrated.dateTime,...
                    calibrated.pm1_predicted_RF,...
                    nodeID,...
                    strcat(timeZone," Time"),...
                    "PM_{1}(\mug/m^{3})",...
                    strcat("PM_{1}(",latitudeString,",",longitudeString,")"),...
                    startDate,endDate,...
                    folderIn,...
                    strcat("PM1_",timeZone,"_Time"),...
                    false,...
                    100 ...
                    )
                
    drawTimeSeriesWithSaveLongRanged(...
                    calibrated.dateTime,...
                    calibrated.pm2_5_predicted_RF,...
                    nodeID,...
                    strcat(timeZone," Time"),...
                    "PM_{2.5}(\mug/m^{3})",...
                    strcat("PM_{2.5}(",latitudeString,",",longitudeString,")"),...
                    startDate,endDate,...
                    folderIn,...
                    strcat("PM2_5_",timeZone,"_Time"),...
                    false,...
                    100 ...
                    )
    
    drawTimeSeriesWithSaveLongRanged(...
                    calibrated.dateTime,...
                    calibrated.pm10_predicted_RF,...
                    nodeID,...
                    strcat(timeZone," Time"),...
                    "PM_{10}(\mug/m^{3})",...
                    strcat("PM_{10}(",latitudeString,",",longitudeString,")"),...
                    startDate,endDate,...
                    folderIn,...
                    strcat("PM10_",timeZone,"_Time"),...
                    false,...
                    100 ...
                    )
                               
    drawTimeSeriesWithSaveLongRanged(...
                    calibrated.dateTime,...
                    calibrated.alveolic_predicted_RF,...
                    nodeID,...
                    strcat(timeZone," Time"),...
                    "Alveolic(\mug/m^{3})",...
                    strcat("Alveolic(",latitudeString,",",longitudeString,")"),...
                    startDate,endDate,...
                    folderIn,...
                    strcat("Alveolic_",timeZone,"_Time"),...
                    false,...
                    100 ...
                    )

    drawTimeSeriesWithSaveLongRanged(...
                    calibrated.dateTime,...
                    calibrated.thoracic_predicted_RF,...
                    nodeID,...
                    strcat(timeZone," Time"),...
                    "Thoracic(\mug/m^{3})",...
                    strcat("Thoracic(",latitudeString,",",longitudeString,")"),...
                    startDate,endDate,...
                    folderIn,...
                    strcat("Thoracic_",timeZone,"_Time"),...
                    false,...
                    100 ...
                    )

    drawTimeSeriesWithSaveLongRanged(...
                    calibrated.dateTime,...
                    calibrated.inhalable_predicted_RF,...
                    nodeID,...
                    strcat(timeZone," Time"),...
                    "Inhalable(\mug/m^{3})",...
                    strcat("Inhalable(",latitudeString,",",longitudeString,")"),...
                    startDate,endDate,...
                    folderIn,...
                    strcat("Inhalable_",timeZone,"_Time"),...
                    false,...
                    100 ...
                    )

                
end

