function currentFileName = getMintsRangeNameStr(startDate,endDate,folder,nodeIDs,nodeIndex,stringIn)

        nodeDataFolder      = folder+ "/"+nodeIDs(nodeIndex);
        currentFileName     = nodeDataFolder+ "/"+...
                                          stringIn+"_"+....
                                            nodeIDs(nodeIndex)+"_"+....
                                                num2str(year(startDate),'%04.f')+"_"+...
                                                    num2str(month(startDate),'%02.f')+"_"+...
                                                        num2str(day(startDate),'%02.f')+"_to_"+...
                                                            num2str(year(endDate),'%04.f')+"_"+...
                                                                num2str(month(endDate),'%02.f')+"_"+...
                                                                    num2str(day(endDate),'%02.f') + ...
                                                                        ".mat";
                                                                        
     if ~exist(fileparts(currentFileName), 'dir')
       mkdir(fileparts(currentFileName));
    end
end