function mintsData = getMintsGPSGPGGA2(fileName)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /media/teamlary/Team_Lary_2/air930/mintsData/raw/001e06305a12/2019/08/11/MINTS_001e06305a12_GPSGPGGA2_2019_08_11.csv
%
% Auto-generated by MATLAB on 25-Aug-2019 17:45:27

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 17);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["dateTime", "timestamp", "latitudeCoordinate", "longitudeCoordinate", "latitude", "latitudeDirection", "longitude", "longitudeDirection", "gpsQuality", "numberOfSatellites", "HorizontalDilution", "altitude", "altitudeUnits", "undulation", "undulationUnits", "age", "stationID"];
opts.VariableTypes = ["string", "datetime", "double", "double", "double", "categorical", "double", "categorical", "double", "double", "double", "double", "categorical", "double", "categorical", "string", "string"];
opts = setvaropts(opts, 2, "InputFormat", "HH:mm:ss");
opts = setvaropts(opts, [1, 16, 17], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 6, 8, 13, 15, 16, 17], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
mintsData = readtable(fileName, opts);


%% Clear temporary variables
clear opts

mintsData.dateTime =   datetime(mintsData.dateTime, 'InputFormat','yyyy-MM-dd HH:mm:ss.SSSSSS' );
mintsData.dateTime.TimeZone = "utc";

mintsData(:,'latitude') = [];
mintsData(:,'longitude') = [];
mintsData(:,'latitudeDirection') = [];
mintsData(:,'longitudeDirection') = [];
mintsData(:,'altitudeUnits') = [];
mintsData(:,'undulationUnits') = [];
mintsData(:,'age') = [];
mintsData(:,'stationID') = [];
mintsData(:,'timestamp') = [];

end

