
function mintsData = getMintsGPSGPRMC2(fileName)
%GETMINTSGPSGPRMC2 Summary of this function goes here
%   Detailed explanation goes here
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /media/teamlary/Team_Lary_2/air930/mintsData/raw/001e06305a12/2019/07/18/MINTS_001e06305a12_GPSGPRMC2_2019_07_18.csv
%
% Auto-generated by MATLAB on 25-Aug-2019 16:13:09

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 14);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["dateTime", "timestamp", "status", "latitudeCoordinate", "longitudeCoordinate", "latitude", "latitudeDirection", "longitude", "longitudeDirection", "speedOverGround", "trueCourse", "dateStamp", "magVariation", "magVariationDirection"];
opts.VariableTypes = ["string", "datetime", "categorical", "double", "double", "double", "categorical", "double", "categorical", "double", "string", "datetime", "string", "string"];
opts = setvaropts(opts, 2, "InputFormat", "HH:mm:ss");
opts = setvaropts(opts, 12, "InputFormat", "yyyy-MM-dd");
opts = setvaropts(opts, [1, 11, 13, 14], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 3, 7, 9, 11, 13, 14], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
mintsData = readtable(fileName, opts);


%% Clear temporary variables
clear opts

mintsData.dateTime =   datetime(mintsData.dateTime, 'InputFormat','yyyy-MM-dd HH:mm:ss.SSSSSS' );
mintsData.dateTime.TimeZone = "utc";

mintsData(:,'latitude') = [];
mintsData(:,'longitude') = [];

mintsData(:,'latitudeDirection') = [];
mintsData(:,'longitudeDirection') = [];

mintsData(:,'trueCourse') = [];

mintsData(:,'status') = [];

mintsData(:,'magVariation') = [];
mintsData(:,'magVariationDirection') = [];

mintsData(:,'timestamp') = [];
mintsData(:,'dateStamp') = [];

end

