
function TCEQ = getTCEQData(filename, dataLines)
%IMPORTFILE Import data from a text file
%  TCEQDATA = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  TCEQDATA = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  TCEQData = importfile("/media/teamlary/Team_Lary_2/air930/gitHubRepos/mintsDataAnalysis/FWNode/rangedOutput/TCEQData.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 30-Jun-2019 15:36:48

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 25);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Date", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, 1, "InputFormat", "MM/dd/yyyy");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
TCEQData = readtable(filename, opts);
TCEQData(1,:) = [];

indexIn = 1;
dateTime = datetime;



for rows = 1:height(TCEQData)-1
   for columns = 1:width(TCEQData)
       if columns == 1 
           dateGiven = table2array(TCEQData(rows,columns));
       else
           dateTime(indexIn,1) = dateGiven + minutes(30) + hours(1)*(columns-2) ;
           pm2_5_TCEQ(indexIn,1) = table2array(TCEQData(rows,columns));
           indexIn = indexIn+1;
       end
    
   end
    
end
   
    

TCEQ = timetable(dateTime,pm2_5_TCEQ);



end