function [] = printCSVLongRange(calibrated,wantedOut,longRangedFolder,nodeID,startDate,endDate,stringIn)
%PRINTCSVDAILY Summary of this function goes here
                    
    outCalibrated            = calibrated(:,wantedOut);
    outCalibratedFileName    = strcat(longRangedFolder,...
                                                    "MINTS_",...
                                                     nodeID,...
                                                     "_",stringIn,"_",...
                                                     num2str(year(startDate),'%02d'),"_",...
                                                     num2str(month(startDate),'%02d'),"_",...
                                                     num2str(day(startDate),'%02d'),...
                                                     "_to_", ...                   
                                                     num2str(year(endDate),'%02d'),"_",...
                                                     num2str(month(endDate),'%02d'),"_",...
                                                     num2str(day(endDate),'%02d'),".csv"...
                                                 );  

    mkdir(fileparts(outCalibratedFileName));
    writetimetable(outCalibrated,outCalibratedFileName)
end

