%% Import data from text file.
% Script for importing data from the following text file:
%
%    /media/teamlary/Team_Lary_1/gitGubRepos/Lakitha/mintsAirML/firmware/dataProcessing/aeroqual/AE 1 day 4.csv
%
% To extend the code to different selected data or a different text file, generate a function instead of a script.

% Auto-generated by MATLAB on 2020/08/22 19:32:49

%% Initialize variables.
filename = '/media/teamlary/Team_Lary_1/gitGubRepos/Lakitha/mintsAirML/firmware/dataProcessing/aeroqual/AE 1 day 4.csv';
startRow = 2;

%% Format for each line of text:
%   column1: double (%f)
%	column2: categorical (%C)
%   column3: double (%f)
%	column4: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%2f%4C%5f%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Remove white space around all cell columns.
dataArray{4} = strtrim(dataArray{4});

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post processing code is included. To generate code which works for unimportable data, select unimportable cells in a file and regenerate the script.

%% Create output variable
AE1day4 = table(dataArray{1:end-1}, 'VariableNames', {'Da','teT','ime','MonitorIDLocationIDPM10ppmPM25ppm'});

%% Clear temporary variables
clearvars filename startRow formatSpec fileID dataArray ans;